### ISSUE TITLE
Missing implicit value for num

### ISSUE THREAD

**Issue by kendall** [lambdista/money#1]
Hi,

I'm using yr Money class to represent product prices. I have a bill of products class that calculates totals from line items by summing using map over Vector of line items, etc. Standard stuff. I was using Double as the price, but when I switched to yr Money, I get compile errors:

[error] /Users/k/work/bofe/play/app/models/Life.scala:181: could not find implicit value for parameter num: Numeric[models.BillOfProducts.Price]
[error]     val theTotal = t.map(calcItem).map(_.price).sum

Of course if I say .map(_price.amount).sum instead, it compiles, but then the return type isn't Money any more.

Thoughts?

**Comment by lambdista** [comment]
Hi, 
the compiler is complaining about not finding an implicit value of Numeric[models.BillOfProducts.Price]. Now if you say the price was a Double and then you switched to Money then you just need to provide an implementation of Numeric[Money] and be sure it's available in the scope implicitly. See [Numeric](http://www.scala-lang.org/api/current/#scala.math.Numeric) for more info.

**Comment by kendall** [comment]
Thanks, Scala newbie here. I'll try to figure out how to implement Numeric[Money]. :+1:

**Comment by lambdista** [comment]
No problem. You're welcome and keep hacking! :+1:

**Comment by lambdista** [comment]
Hi,
I implemented Numeric[Money]. See README for details.

**Comment by lambdista** [comment]
Having problems publishing the 0.2.0 version to the OSSRH repo. I'll close this issue when I'm done. However, for now, you could just use the 0.1.0 version and copy/paste my implementation of Numeric[Money].

**Comment by kendall** [comment]
I implemented it yesterday, too. Slightly differently. I also implemented
Ordering. I'll use yrs as soon as you get 020 pub'd.

Cheers!

**Comment by lambdista** [comment]
Published.

Cheers!

**Comment by kendall** [comment]
awesome, updated and tests pass :+1:
