### ISSUE TITLE
equality?

### ISSUE THREAD

**Issue by kendall** [lambdista/money#2]
I probably don't need to test this but:

`[info] - must convert to GBP from USD correctly *** FAILED ***`
`[info]   356921.16698 GBP was not equal to 356921.16698 GBP (ModelSpec.scala:115)`

**Comment by lambdista** [comment]
Sorry but I cannot guess what's happening. I need  to see the code behind that.

**Comment by lambdista** [comment]
Hi,
there was some issues with equality. I released version 0.3.0. See [release notes](https://github.com/lambdista/money/releases/tag/v0.3.0) for more info.

**Comment by kendall** [comment]
Cool. My test fails went away. :)
